<html>
    <head>
        <title> My First Webpage </title>
        <link rel="stylesheet" type="text/css" href="../style.css" />
        <script type="text/javascript" src="../jsc3d/jsc3d.js"></script>
        <script type="text/javascript" src="../jsc3d/jsc3d.webgl.js"></script>
        <script type="text/javascript" src="../jsc3d/jsc3d.touch.js"></script>
    </head>

    <body>
        <div id = "container">
            <div id = "header">
                <h1> Computer Aided Design </h1>
            </div>

            <div id = "content">
                <div id = "nav">
                    <ul>
                        <li> <a href = "../index.html"> Home </a> </li>
                        <li> <a href = "tools.html"> Safety and tools </a> </li>
                        <li> <a href = "HTML.html"> HTML </a></li>
                        <li> <a href = "CSS.html"> CSS </a></li>
                        <li> <a href = "development.html"> Website Development</a></li>
                        <li> <a href = "git.html"> Using Git</a></li>
                        <li> <a href = "gimp.html"> Computer Graphics</a></li>
                        <li> <a href = "CAD.html"> CAD</a></li>
                        <li> <a class = "selected" href = "models.html"> Fusion Models</a></li>
                    </ul>
                </div>
                
                <div id = "main">
                    <h3>Nametag</h3>
                    <p class = "comment">Sketching, Extruding, Text, Fillet</p>
                    <ol>
                        <li>Create a sketch and used a rectangle, an arc and a circle to create the shape  of the nametag. </li>
                        <a href = "../photos/model/nt_sketch1.jpg" target="_blank"> <img src = "../photos/model/nt_sketch1.jpg" width = "400"/></a>
                        <li>Include the relevant dimensions of the nametag before using the command Extrude to turn the sketch into a 3 dimensional body by creating a height to the nametag. I extruded the edge by main body by 2mm, and the edge by 3mm. </li>
                        <li>Creat a hole for the key ring of diameter 2.5mm. </li>
                        <li>Creat another sketch to put my name in using the Create Text function to put my name before extruding it by 1mm. </li>
                        <a href = "../photos/model/nt_sketch2.jpg" target="_blank"> <img src = "../photos/model/nt_sketch2.jpg" width = "400"/></a>
                        <li>Round off the corners using the Fillet command by 2mm for the outer corner, and 1mm for the inner corner. </li>
                    </ol>
                    <p class = "comment">The Finished Product</p>
                        <a href = "../photos/model/Nametag.png" target="_blank"> <img src = "../photos/model/Nametag.png" width = "500"/></a>
              
                    <hr/>
                    <h3> Fidget Spinner</h3>
                    <p class = "comment"> Revolve, Pattern. Houses a ABEC 608 Bearing and 3 M8 stainless steel hex nuts. </p>
                    <ol>
                        <li> Start with a sketch with a circle of diameter 40mm as a limit to how big the fidget spinner is, before designing one arm of the fidget spinner using a hexagon to house the nut, a circle for the centre, and 2 lines tangent to the circle for the arm. </li>
                        <a href = "../photos/model/fs_sketch1.png" target="_blank"> <img src = "../photos/model/fs_sketch1.png" width = "300"/></a>
                        <li> Extrude one arm by 8mm</li>
                        <li> Create a groove for aesthetics and fillet the inner radius. </li>
                        <a href = "../photos/model/fs_sketch2.jpg" target="_blank"> <img src = "../photos/model/fs_sketch2.jpg" width = "200"/></a>
                        <li> Create another sketch for a taper in the arm and revolve cut the arm about the Z axie</li>
                        <a href = "../photos/model/fs_sketch3.png" target="_blank"> <img src = "../photos/model/fs_sketch3.png" height = "100"/></a>
                        <a href = "../photos/model/revolve.jpg" target="_blank"> <img src = "../photos/model/revolve.jpg" height = "100"/></a>
                        <li> Use Pattern - Circular to duplicate the arm 2 more times around an the Z-axis and combined the 3 different arms together as one body </li>
                        <li> Fillet of 12mm between the 3 arms. </li>
                    </ol>
                    <p class = "comment">The Finished Product</p>
                    <a href = "../photos/model/spinner.png" target="_blank"> <img src = "../photos/model/spinner.png" width = "400"/></a>
                    <hr/>
                
                    <h3> Knight Chess Piece</h3>
                    <p class="comment">Canvas, Fit Point Spline tool. </p>
                    <ol>
                        <li> Start by importing an image of a Knight Chess piece into Fusion. </li>
                        <a href = "../photos/model/knight.png" target="_blank"> <img src = "../photos/model/knight.png" height = "200"/></a>
                        <a href = "../photos/model/canvas.jpg" target="_blank"> <img src = "../photos/model/canvas.jpg" height = "200"/></a>
                        <li> Start a sketch to model the base. I used the Line tool and Fit Point Spline tool to model one half of the base before revolving it</li>
                        <a href = "../photos/model/base.jpg" target="_blank"> <img src = "../photos/model/base.jpg" height = "160"/></a>
                        <a href = "../photos/model/knight_revolve.jpg" target="_blank"> <img src = "../photos/model/knight_revolve.jpg" height = "160"/></a>
                        <li> Create a sketch with the shape of the horse using the Fit Point Spline Tool. I then extrude the body of the horse by 1mm with a Symmetric direction, and the mane of the horse by 0.5mm.</li>
                        <a href = "../photos/model/knight_sketch.jpg" target="_blank"> <img src = "../photos/model/knight_sketch.jpg" height = "160"/></a>
                        <a href = "../photos/model/knight_extrude.jpg" target="_blank"> <img src = "../photos/model/knight_extrude.jpg" height = "160"/></a>   
                    </ol>
                    <hr/>
                    
                    <h3>Laptop Stand</h3>
                    <p class="comment">Components, Parametric Modelling. </p>
                    <ol>
                        <li>Start by inputting the User parameters such as the material thickness, length and width. </li>
                        <a href = "../photos/model/ls_parameters.jpg" target="_blank"><img src = "../photos/model/ls_parameters.jpg" height = "200"/></a>
                        <li>Create a new component called "Leg" and started a sketch with the following dimensions.  </li>
                        <a href = "../photos/model/ls_sketch1.jpg" target="_blank"><img src = "../photos/model/ls_sketch1.jpg" width = "350"/></a>
                        <li>Extrude the sketch of the leg by "t" which is the user parameter for the thickness of the leg</li>
                        <a href = "../photos/model/ls_leg.jpg" target="_blank"><img src = "../photos/model/ls_leg.jpg" height = "200"/></a>
                        <li>Copy and paste the component "Leg" to create the second one. Joint the 2 surfaces of the 2 legs, and specify the offset by 325mm. Fillet the top edges by 3mm to round the sharp edges. </li>
                        <a href = "../photos/model/ls_legs.jpg" target="_blank"><img src = "../photos/model/ls_legs.jpg" width = "350"/></a>
                        <li>Create a new component "Top" and start a sketch on the top surface of the original leg by creating a rectangle.. In order to secure the top onto the legs, we would use 4 rectangular holes in the top and 4 tabs in the leg. Create 4 smaller slots as holes for the tabs to go through.  </li>
                        <a href = "../photos/model/ls_top.jpg" target="_blank"><img src = "../photos/model/ls_top.jpg" width = "350"/></a>
                        <li>Extrude the top by the material thickness downwards into the legs. (ensure that the 4 rectangular holes are not selected)</li>
                        <a href = "../photos/model/ls_extrude.jpg" target="_blank"><img src = "../photos/model/ls_extrude.jpg" width = "350"/></a>
                        <li>To create the tabs in the legs and remove material  of the leg that intersects the top, use the combine function. Select the original leg as the target body (the component you are changing) and the top as the tool body (the component you are using to change the target body). Use the "Cut" operation and check the box which says "Keep Tools". Since the 2nd leg is a copy of the first leg, the changes made to the 1st leg will also be reflected into the 2nd one. Fillet the external corners by 2mm, and the corners of the tabs on the legs by 0.5mm</li>
                        <a href = "../photos/model/ls_combine.jpg" target="_blank"><img src = "../photos/model/ls_combine.jpg" width = "350"/></a>
                        <a href = "../photos/model/ls_intersect.jpg" target="_blank"><img src = "../photos/model/ls_intersect.jpg" width = "350"/></a>
                        <li>Create a new component "Support" and a new plane where we would sketch our support. The plane is created by Offset from the back of the leg by a distance of 45mm</li>
                        <a href = "../photos/model/ls_newplane1.jpg" target="_blank"><img src = "../photos/model/ls_newplane1.jpg" width = "500"/></a>
                        <li>Create a rectangle and dimension it. Draw a horizontal line to divide the rectangle into 2 equal piece. This will help create 2 rectangle at the top half of the support that will serve as slots to fit the support into the legs. </li>
                        <a href = "../photos/model/ls_support.jpg" target="_blank"><img src = "../photos/model/ls_support.jpg" width = "500"/></a>
                        <li>Extrude the support symmetrically (extrudes the sketch both side) by the "t/2", which is half of the thickness of the material. Ensure that you do not select the 2 small rectangles that will serve as tabs. </li>
                        <a href = "../photos/model/ls_extrude2.jpg" target="_blank"><img src = "../photos/model/ls_extrude2.jpg" width = "500"/></a>
                        <li>To create the 2nd support, we will create a new plane that will serve as a mirror plane to mirror the original support. Construct a midplane and select the front and the back of the leg to create a plane in the middle of the leg</li>
                        <a href = "../photos/model/ls_newplane2.jpg" target="_blank"><img src = "../photos/model/ls_newplane2.jpg" width = "500"/></a>
                        <li>Create > Mirror the body: Support and use the previously constructed midplane as a mirror plane. Fillet the corners by 2mm</li>
                        <a href = "../photos/model/ls_mirror.jpg" target="_blank"><img src = "../photos/model/ls_mirror.jpg" width = "500"/></a>
                        <li>To create the slots in the legs, use the combine function. Select the original leg as the target body and the 2 support as the tool body. Use "cut" operation and check the box "Keep Tools. Fillet the internal corners of the slots by 0.5mm to make sliding the support into the legs easier. </li>
                        <a href = "../photos/model/ls_intersect2.jpg" target="_blank"><img src = "../photos/model/ls_intersect2.jpg" width = "500"/></a>
                        <li>To laser cut the leg, create a new sketch of the leg, and click finish sketch. Do this for all 3 different parts. You then can right click the sketch in the Broswer, and save the sketch as a different file format to laser cut. </li>
                        <a href = "../photos/model/ls_sketchforlasercutting.jpg" target="_blank"><img src = "../photos/model/ls_sketchforlasercutting.jpg" width = "500"/></a>
                        <li>To show how my laptop would look like on the stand, I created a new component and used sketch, champfer and extrude to model my laptop with the same dimensions before <a href = "https://youtu.be/Sj5d7CiZkjQ" target ="_blank">animating the construction of the laptop stand</a></li>
                    </ol>
                </div>
            </div>

            <div id = "footer">
                <p> Copyright © Emmanuel Cheng </p>
            </div>
        </div>
    </body>
</html>